### ISSUE TITLE
Context window persists dragging

### ISSUE THREAD

**Issue by KevinBatdorf** [blaze-slider/blaze-slider#1]
I looked at the implementation only briefly, but it's likely related to the context menu triggering the pointer event.

https://codesandbox.io/s/blaze-slider-playground-ps0b9u

https://user-images.githubusercontent.com/1478421/179335396-5287198e-57e5-46b7-ad1a-cde167125a6a.mov

**Comment by MananTank** [comment]
Hi @KevinBatdorf. Thanks for creating this issue! 

I got super busy with other stuff and completely forgot about this. I have fixed a bunch of issues in ios Safari and the issue you mentioned above.

**Comment by ansmlc** [comment]
Hi @MananTank I'm not totally sure if this is the right place. But I think I have a similar issue on my laptop with touchpad. It doesn't happen when I try it on your demo examples, but it happens on my fresh install on a Gatsby site, running locally in a dev build.

**I'll try to explain; On my local build:**
Clicking on the slider seems to _toggle_ dragging mode. At this point, I have to _release_ the click in order to drag/slide images. I also have to _click/tap again_ in order to exit this drag-mode. In other words, I can't click & hold / drag in order to drag/slide images. 

**On your demos (working as expected):**
Clicking, holding & dragging moves the slider, while releasing the click also "releases" the image, making it snap freely into position.

I'd appreciate any help.

**Comment by MananTank** [comment]
@ansmlc Can you share a video recording of this or a live demo link?

**Comment by chicharitomagnetico** [comment]
Hi @MananTank and @ansmlc, 
Sorry to jump into this thread. If I read correctly, this is happening on my side too.

https://user-images.githubusercontent.com/11357878/204061728-9197c16e-fd02-45af-aa01-da0ca1a7ede5.mp4

**Comment by MananTank** [comment]
@chicharitomagnetico Looks like the issue you are having is with image dragging. set `draggable="false"` on img element to fix that issue.

Example: `<img draggable="false" src="image.png">`

**Comment by chicharitomagnetico** [comment]
That did the trick!
Thanks @MananTank
