### ISSUE TITLE
slide order glitch

### ISSUE THREAD

**Issue by robjstanley** [blaze-slider/blaze-slider#24]
We're seeing some issue on mobile when dragging the slider intermittently the slides end up out of their original order.

At around 4 seconds in dragging to previous slide jumps two slides, and slide 1 is sent to the end of the list and slide 2 becomes slide 1.

https://user-images.githubusercontent.com/1289058/201905019-da4f32c3-acfb-4ee9-8fbb-a3381f079f1f.MOV

https://383hhjb8piaeifwj-62197366962.shopifypreview.com

**Comment by robjstanley** [comment]
@MananTank any thoughts on this?

**Comment by MananTank** [comment]
Hi @robjstanley, Sorry I missed notification for this. 
Can you send a new link? - the link you added previously is expired

**Comment by MananTank** [comment]
This issue was caused because slider was being refreshed because of viewport resizing. 

In iOS when you scroll down the viewport is resized and viewport's height changes. slider refresh should have only been triggered when viewport's width is updated - height changes should have been ignored. 

I have fixed this issue in v1.8.1
@robjstanley please update the version to 1.8.1 to get the fix

**Comment by robjstanley** [comment]
@MananTank thank you for fixing the bug so quickly!
