### ISSUE TITLE
Unable to start dev server

### ISSUE THREAD

**Issue by onderbakirtas** [blaze-slider/blaze-slider#52]
Hello there. I'd like to know how to start dev server for development of this package. Running `dev` script gives error written below. Thanks in advance.

```
npm ERR! No workspaces found:
npm ERR!   --workspace=fixtures/blaze-slider-test
```

**Comment by MananTank** [comment]
Sorry for a super late response here, 
`dev` script is just for starting the dev server of a test project when developing - `fixtures/blaze-slider-test` is not committed in repo, You can create that folder and setup the library using relative imports ( instead of importing from `blaze-slider` npm package - you would import from local folder )
