### ISSUE TITLE
blaze slider not updating dynamically when props changes

### ISSUE THREAD

**Issue by gsharath** [blaze-slider/blaze-slider#58]
I am using blaze slider in react. I need to display dynamic sliders based on button clicks.
I tried below approach but it just says below message

> slidesToShow can not be larger than number of slides. Setting slidesToShow = totalSlides instead.

https://codesandbox.io/s/react-blaze-slider-forked-gm63ds?file=/src/App.jsx

**Comment by notflip** [comment]
Did you ever get a response? Can we assume this project is dead? No responses and no code push since 2022

**Comment by gsharath** [comment]
nope :(

**Comment by MananTank** [comment]
Sorry, I have very busy with my work lately so I could not respond. 

@gsharath Here's a modified version of your sandbox with dynamic sliders using `refresh` method ( https://blaze-slider.dev/docs/api/methods#refresh )

https://codesandbox.io/s/react-blaze-slider-forked-ml8gfm?file=/src/App.jsx

In your sandbox `slidesToShow` is set to `1000` which is larger than the number of slides (3) - that's why you are getting that warning. You can not show 1000 slides if you only have 3 slides
